volumes:
  data:
services:
  builder:
    build:
      target: builder
      context: .
  ctl:
    build:
      target: ctl
      context: .
    volumes:
      - data:/data/ctl
    ports:
      - 50052:50052
    environment:
      - obs.enabled=false
      - ctl.addr=:50052
      - log.level=0
      - log.console.enabled=true
      - log.file.enabled=true
      - log.file.name={workdir}/log/ctl.log
      - log.file.dir=log
      - workdir=/data/ctl
  exec:
    build:
      target: exec
      context: .
    volumes:
      - data:/data/executor
    environment:
      - executor.addr=:9595
      - queue.host=queue:50051
      - ctl.host=ctl:50052
      - repo.host=repo:50053
      - recorder.host=recorder:50054
      - max.queue.errors=2
      - metadata.enabled=false
      - obs.enabled=false
      - log.level=0
      - log.console.enabled=true
      - log.file.enabled=false
      - workdir=/data/executor
    depends_on:
      - ctl
      - queue
      - recorder
      - repo

  listener:
    build:
      target: listener
      context: .
    ports:
      - 8080:8080
    volumes:
      - data:/data/listener
    environment:
      - listener.addr=:8080
      - queue.host=queue:50051
      - ctl.host=ctl:50052
      - repo.host=repo:50053
      - recorder.host=recorder:50054
      - max.queue.errors=2
      - metadata.enabled=false
      - obs.enabled=false
      - log.level=0
      - log.console.enabled=true
      - log.file.enabled=false
      - workdir=/data/listener
    depends_on:
      - ctl
      - queue
      - recorder
      - repo

  queue:
    build:
      target: queue
      context: .
    ports:
      - 50051
    volumes:
      - data:/data/queue
    environment:
      - queue.addr=:50051
      - ctl.host=ctl:50052
      - repo.host=repo:50053
      - recorder.host=recorder:50054
      - max.queue.errors=2
      - metadata.enabled=false
      - obs.enabled=false
      - log.level=0
      - log.console.enabled=true
      - log.file.enabled=false
      - workdir=/data/queue
    depends_on:
      - ctl

  recorder:
    build:
      target: recorder
      context: .
    ports:
      - 50054:50054
    volumes:
      - data:/data/recorder
    environment:
      - recorder.addr=:50054
      - queue.host=queue:50051
      - ctl.host=ctl:50052
      - repo.host=repo:50053
      - max.queue.errors=2
      - metadata.enabled=false
      - obs.enabled=false
      - log.level=0
      - log.console.enabled=true
      - log.file.enabled=false
      - workdir=/data/recorder
    depends_on:
      - ctl

  repo:
    build:
      target: repo
      context: .
    ports:
      - 50053:50053
    volumes:
      - data:/data/repo
    environment:
      - repo.addr=:50053
      - queue.host=queue:50051
      - ctl.host=ctl:50052
      - recorder.host=recorder:50054
      - max.queue.errors=2
      - metadata.enabled=false
      - obs.enabled=false
      - log.level=0
      - log.console.enabled=true
      - log.file.enabled=false
      - workdir=/data/repo
    depends_on:
      - ctl