apiVersion: v1
kind: Namespace
metadata:
  name: jobico
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ctl-sfs
  namespace: jobico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ctl
  template:
    metadata:
      labels:
        app: ctl
    spec:
      containers:
      - name: ctl
        image: jobico/ctl:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 50052
          hostPort: 50052
          protocol: TCP
        volumeMounts:
        - name: ctl-data
          mountPath: /usr/share/jobico/ctl
        env:
        - name: ctl.addr
          value: "localhost:50052"
        - name: prof.enabled
          value: "false"
        - name: pprof.addr
          value: "localhost:7575"
        - name: log.level
          value: "1"
        - name: log.console.enabled
          value: "false"
        - name: log.file.enabled
          value: "false"
        - name: obs.enabled
          value: "false"
        - name: workdir
          value: "/usr/share/jobico/ctl"
  volumeClaimTemplates:
    - metadata:
        name: ctl-data
        namespace: jobico
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: ctl-svc
  namespace: jobico
spec:
  selector:
    app: ctl
  ports:
    - name: "50052"
      port: 50052
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ctl-ingress
  namespace: jobico
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - ctl
  rules:
    - host: ctl
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ctl-svc
                port:
                  number: 50052