apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue
  namespace: jobico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: jobico/queue:latest
        imagePullPolicy: Never
        ports:
        - name: api
          containerPort: 50051
        - name: pprof
          containerPort: 6060
        volumeMounts:
          - name: queue-data
            mountPath: /usr/share/jobico/queue
        env:
        - name: queue.addr
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: queue.addr
              optional: false
        - name: ctl.host
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: ctl.host
              optional: false
        - name: prof.enabled
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: prof.enabled
              optional: true
        - name: pprof.addr
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: pprof.addr
              optional: true
        - name: log.level
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: log.level
              optional: true
        - name: log.console.enabled
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: log.console.enabled
              optional: true
        - name: log.file.enabled
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: log.file.enabled
              optional: true
        - name: obs.enabled
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: obs.enabled
              optional: true
        - name: obs.exporter.trace.grpc.host
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: obs.exporter.trace.grpc.host
              optional: true
        - name: obs.exporter.metrics.http.host
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: obs.exporter.metrics.http.host
              optional: true
        - name: obs.exporter.metrics.host.path
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: obs.exporter.metrics.host.path
              optional: true
        - name: jobs.metrics.host
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: obs.metrics.host
              optional: true
        - name: jobs.metrics.runtime
          valueFrom:
            configMapKeyRef:
              name: jobico-config
              key: jobs.metrics.runtime
              optional: true        
        - name: workdir
          value: "/usr/share/jobico/queue"
  volumeClaimTemplates:
    - metadata:
        name: queue-data
        namespace: jobico
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name: queue
  namespace: jobico
spec:
  selector:
    app: queue
  ports:
    - name: api
      port: 50051
      targetPort: api
    - name: pprof
      port: 6060
      targetPort: pprof
  type: ClusterIP

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
  name: queue-ingress-grpc
  namespace: jobico
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - queue
      secretName: queue-cert
  rules:
    - host: queue
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: queue
                port:
                  number: 50051

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  name: queue-ingress-http
  namespace: jobico
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - queue
      secretName: queue-cert
  rules:
    - host: queue
      http:
        paths:
          - path: /debug/
            pathType: Prefix
            backend:
              service:
                name: queue
                port:
                  number: 6060