apiVersion: v1
kind: Namespace
metadata:
  name: jobico

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: queue-sfs
  namespace: jobico
spec:
  replicas: 1
  selector:
    matchLabels:
      app: queue
  template:
    metadata:
      labels:
        app: queue
    spec:
      containers:
      - name: queue
        image: jobico/queue:latest
        imagePullPolicy: Never
        ports:
          - containerPort: 50051
            hostPort: 50051
            protocol: TCP
        volumeMounts:
          - name: queue-data
            mountPath: /usr/share/jobico/queue
        env:
        - name: queue.addr
          value: "localhost:50051"
        - name: ctl.host
          value: "ctl:50052"
        - name: prof.enabled
          value: "false"
        - name: pprof.addr
          value: "localhost:7575"
        - name: log.level
          value: "1"
        - name: log.console.enabled
          value: "false"
        - name: log.file.enabled
          value: "false"
        - name: obs.enabled
          value: "false"
        - name: workdir
          value: "/usr/share/jobico/queue"
  volumeClaimTemplates:
    - metadata:
        name: queue-data
        namespace: jobico
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi


---

apiVersion: v1
kind: Service
metadata:
  name: queue-svc
  namespace: jobico
spec:
  selector:
    app: queue
  ports:
    - name: "50051"
      port: 50051
  type: ClusterIP