version: '3.9'
x-default-logging: &logging
  driver: "json-file"
  options:
    max-size: "5m"
    max-file: "2"

networks:
  default:
    name: obs
    driver: bridge

services:
  prometheus:
    image: quay.io/prometheus/prometheus:latest
    # container_name: prometheus
    command:
      # - --web.console.templates=/etc/prometheus/consoles
      # - --web.console.libraries=/etc/prometheus/console_libraries
      # - --storage.tsdb.retention.time=1h
      - --config.file=/etc/prometheus/prometheus-config.yaml
      # - --storage.tsdb.path=/prometheus
      # - --web.enable-lifecycle
      # - --web.route-prefix=/
      # - --enable-feature=exemplar-storage
      - --enable-feature=otlp-write-receiver
      # - --enable-feature=otlp-write-receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus-config.yaml
    deploy:
      resources:
        limits:
          memory: 300M
    ports:
      - "9090:9090"
    logging: *logging
  jaeger:
    image: jaegertracing/all-in-one:1.51
    # container_name: jaeger
    command:
      # - "--memory.max-traces=8000"
      # - "--query.base-path=/jaeger/ui"
      # - "--prometheus.server-url=http://${PROMETHEUS_ADDR}"
      # - "--prometheus.query.normalize-calls=true"
      # - "--prometheus.query.normalize-duration=true"
    deploy:
      resources:
        limits:
          memory: 300M
    restart: unless-stopped
    ports:
      - "16686:16686"         # Jaeger UI
      - "4317:4317"
      - "4318:4318"                         
    # environment:
      # - METRICS_STORAGE_TYPE=prometheus
    logging: *logging